# Generated by Django 4.1.4 on 2022-12-10 07:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_alter_routine_created_at_alter_routineday_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 16, 31, 22, 584289)),
        ),
        migrations.AlterField(
            model_name='routineday',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 16, 31, 22, 599918)),
        ),
        migrations.AlterField(
            model_name='routineday',
            name='day',
            field=models.CharField(choices=[('MON', 'MON'), ('TUE', 'TUE'), ('WED', 'WED'), ('THU', 'THU'), ('FRI', 'FRI'), ('SAT', 'SAT'), ('SUN', 'SUN')], max_length=3),
        ),
        migrations.AlterField(
            model_name='routineresult',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 16, 31, 22, 599918)),
        ),
        migrations.AlterField(
            model_name='routineresult',
            name='routine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='routine.routine'),
        ),
    ]
